/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  home: () => import("@/views/home/index.vue"),
  external: () => import("@/views/external/index.vue"),
  "material_code-rule": () => import("@/views/material/code-rule/index.vue"),
  material_material: () => import("@/views/material/material/index.vue"),
  material_unit: () => import("@/views/material/unit/index.vue"),
  "mold-product_color": () => import("@/views/mold-product/color/index.vue"),
  "mold-product_erpnext-mapping": () => import("@/views/mold-product/erpnext-mapping/index.vue"),
  "mold-product_mold-code": () => import("@/views/mold-product/mold-code/index.vue"),
  "mold-product_mold-material": () => import("@/views/mold-product/mold-material/index.vue"),
  "mold-product_mold": () => import("@/views/mold-product/mold/index.vue"),
  "mold-product_phone-model": () => import("@/views/mold-product/phone-model/index.vue"),
  "mold-product_product-code": () => import("@/views/mold-product/product-code/index.vue"),
  "mold-product_product": () => import("@/views/mold-product/product/index.vue"),
  oa_approval: () => import("@/views/oa/approval/index.vue"),
  "oa_box-label": () => import("@/views/oa/box-label/index.vue"),
  system_access_permission: () => import("@/views/system/access/permission/index.vue"),
  system_access_role: () => import("@/views/system/access/role/index.vue"),
  system_access_user: () => import("@/views/system/access/user/index.vue"),
  system_operations_audit: () => import("@/views/system/operations/audit/index.vue"),
  "system_operations_erpnext-sync-log": () => import("@/views/system/operations/erpnext-sync-log/index.vue"),
  "system_sso_external-system": () => import("@/views/system/sso/external-system/index.vue"),
  "system_sso_oauth2-binding": () => import("@/views/system/sso/oauth2-binding/index.vue"),
  "system_sso_oauth2-client": () => import("@/views/system/sso/oauth2-client/index.vue"),
};
