/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1,
      hideInMenu: true
    }
  },
  {
    name: 'external',
    path: '/external',
    component: 'layout.base$view.external',
    meta: {
      title: 'external',
      i18nKey: 'route.external',
      icon: 'mdi:apps-box',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat|oauth-consent)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'material',
    path: '/material',
    component: 'layout.base',
    meta: {
      title: 'material',
      i18nKey: 'route.material',
      icon: 'mdi:package-variant-closed',
      order: 2
    },
    children: [
      {
        name: 'material_code-rule',
        path: '/material/code-rule',
        component: 'view.material_code-rule',
        meta: {
          title: 'material_code-rule',
          i18nKey: 'route.material_code-rule',
          permission: 'eims:material:code-rule'
        }
      },
      {
        name: 'material_material',
        path: '/material/material',
        component: 'view.material_material',
        meta: {
          title: 'material_material',
          i18nKey: 'route.material_material',
          permission: 'eims:material:material'
        }
      },
      {
        name: 'material_unit',
        path: '/material/unit',
        component: 'view.material_unit',
        meta: {
          title: 'material_unit',
          i18nKey: 'route.material_unit',
          permission: 'eims:material:unit'
        }
      }
    ]
  },
  {
    name: 'mold-product',
    path: '/mold-product',
    component: 'layout.base',
    meta: {
      title: 'mold-product',
      i18nKey: 'route.mold-product',
      icon: 'mdi:cube-outline',
      order: 3
    },
    children: [
      {
        name: 'mold-product_color',
        path: '/mold-product/color',
        component: 'view.mold-product_color',
        meta: {
          title: 'mold-product_color',
          i18nKey: 'route.mold-product_color',
          permission: 'eims:mold:color'
        }
      },
      {
        name: 'mold-product_erpnext-mapping',
        path: '/mold-product/erpnext-mapping',
        component: 'view.mold-product_erpnext-mapping',
        meta: {
          title: 'mold-product_erpnext-mapping',
          i18nKey: 'route.mold-product_erpnext-mapping',
          permission: 'eims:mold:erpnext-mapping'
        }
      },
      {
        name: 'mold-product_mold',
        path: '/mold-product/mold',
        component: 'view.mold-product_mold',
        meta: {
          title: 'mold-product_mold',
          i18nKey: 'route.mold-product_mold',
          permission: 'eims:mold:mold'
        }
      },
      {
        name: 'mold-product_mold-code',
        path: '/mold-product/mold-code',
        component: 'view.mold-product_mold-code',
        meta: {
          title: 'mold-product_mold-code',
          i18nKey: 'route.mold-product_mold-code',
          permission: 'eims:mold:mold-code'
        }
      },
      {
        name: 'mold-product_mold-material',
        path: '/mold-product/mold-material',
        component: 'view.mold-product_mold-material',
        meta: {
          title: 'mold-product_mold-material',
          i18nKey: 'route.mold-product_mold-material',
          permission: 'eims:mold:mold-material'
        }
      },
      {
        name: 'mold-product_phone-model',
        path: '/mold-product/phone-model',
        component: 'view.mold-product_phone-model',
        meta: {
          title: 'mold-product_phone-model',
          i18nKey: 'route.mold-product_phone-model',
          permission: 'eims:mold:phone-model'
        }
      },
      {
        name: 'mold-product_product',
        path: '/mold-product/product',
        component: 'view.mold-product_product',
        meta: {
          title: 'mold-product_product',
          i18nKey: 'route.mold-product_product',
          permission: 'eims:mold:product'
        }
      },
      {
        name: 'mold-product_product-code',
        path: '/mold-product/product-code',
        component: 'view.mold-product_product-code',
        meta: {
          title: 'mold-product_product-code',
          i18nKey: 'route.mold-product_product-code',
          permission: 'eims:mold:product-code'
        }
      }
    ]
  },
  {
    name: 'oa',
    path: '/oa',
    component: 'layout.base',
    meta: {
      title: 'oa',
      i18nKey: 'route.oa',
      icon: 'mdi:clipboard-check',
      order: 5
    },
    children: [
      {
        name: 'oa_approval',
        path: '/oa/approval',
        component: 'view.oa_approval',
        meta: {
          title: 'oa_approval',
          i18nKey: 'route.oa_approval',
          permission: 'eims:oa:approval'
        }
      },
      {
        name: 'oa_box-label',
        path: '/oa/box-label',
        component: 'view.oa_box-label',
        meta: {
          title: 'oa_box-label',
          i18nKey: 'route.oa_box-label',
          permission: 'eims:oa:box-label'
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system'
    },
    children: [
      {
        name: 'system_access',
        path: '/system/access',
        meta: {
          title: 'system_access',
          i18nKey: 'route.system_access',
          icon: 'mdi:account-cog-outline',
          order: 10
        },
        children: [
          {
            name: 'system_access_permission',
            path: '/system/permission',
            component: 'view.system_access_permission',
            meta: {
              title: 'system_access_permission',
              i18nKey: 'route.system_access_permission',
              icon: 'mdi:shield-key-outline',
              order: 30,
              permission: 'eims:system:permission',
              roles: ['R_SUPER', 'R_ADMIN']
            }
          },
          {
            name: 'system_access_role',
            path: '/system/role',
            component: 'view.system_access_role',
            meta: {
              title: 'system_access_role',
              i18nKey: 'route.system_access_role',
              icon: 'mdi:account-key-outline',
              order: 20,
              permission: 'eims:system:role',
              roles: ['R_SUPER', 'R_ADMIN']
            }
          },
          {
            name: 'system_access_user',
            path: '/system/user',
            component: 'view.system_access_user',
            meta: {
              title: 'system_access_user',
              i18nKey: 'route.system_access_user',
              icon: 'mdi:account-multiple-outline',
              order: 10,
              permission: 'eims:system:user',
              roles: ['R_SUPER', 'R_ADMIN']
            }
          }
        ]
      },
      {
        name: 'system_operations',
        path: '/system/operations',
        meta: {
          title: 'system_operations',
          i18nKey: 'route.system_operations',
          icon: 'mdi:clipboard-pulse-outline',
          order: 30
        },
        children: [
          {
            name: 'system_operations_audit',
            path: '/system/audit',
            component: 'view.system_operations_audit',
            meta: {
              title: 'system_operations_audit',
              i18nKey: 'route.system_operations_audit',
              icon: 'mdi:clipboard-text-clock-outline',
              order: 10,
              permission: 'eims:system:audit',
              roles: ['R_SUPER', 'R_ADMIN']
            }
          },
          {
            name: 'system_operations_erpnext-sync-log',
            path: '/system/erpnext-sync-log',
            component: 'view.system_operations_erpnext-sync-log',
            meta: {
              title: 'system_operations_erpnext-sync-log',
              i18nKey: 'route.system_operations_erpnext-sync-log',
              icon: 'mdi:clipboard-text-outline',
              order: 20,
              permission: 'eims:system:erpnext-sync-log'
            }
          }
        ]
      },
      {
        name: 'system_sso',
        path: '/system/sso',
        meta: {
          title: 'system_sso',
          i18nKey: 'route.system_sso',
          icon: 'mdi:key-link',
          order: 20
        },
        children: [
          {
            name: 'system_sso_external-system',
            path: '/system/external-system',
            component: 'view.system_sso_external-system',
            meta: {
              title: 'system_sso_external-system',
              i18nKey: 'route.system_sso_external-system',
              icon: 'mdi:apps-box',
              order: 10,
              permission: 'eims:system:external-system',
              roles: ['R_SUPER', 'R_ADMIN']
            }
          },
          {
            name: 'system_sso_oauth2-binding',
            path: '/system/oauth2-binding',
            component: 'view.system_sso_oauth2-binding',
            meta: {
              title: 'system_sso_oauth2-binding',
              i18nKey: 'route.system_sso_oauth2-binding',
              icon: 'mdi:link-variant',
              order: 30,
              permission: 'eims:system:oauth2-binding',
              roles: ['R_SUPER', 'R_ADMIN']
            }
          },
          {
            name: 'system_sso_oauth2-client',
            path: '/system/oauth2-client',
            component: 'view.system_sso_oauth2-client',
            meta: {
              title: 'system_sso_oauth2-client',
              i18nKey: 'route.system_sso_oauth2-client',
              icon: 'mdi:key-chain-variant',
              order: 20,
              permission: 'eims:system:oauth2-client',
              roles: ['R_SUPER', 'R_ADMIN']
            }
          }
        ]
      }
    ]
  }
];
